### ISSUE TITLE
Add mouse bindings too?

### ISSUE THREAD

**Issue by Droyk** [Dudemanguy/mpv-manga-reader#14]
I forgot to see the controls & started wheel scrolling to my surprise the script only supports the keyboard bindings!
Can you please also add controls/bindings for the mouse too?

**Comment by Dudemanguy** [comment]
Those are just the defaults. You can add any bindings you want in input.conf. Read up how it works by looking at the mpv manual.

**Comment by Droyk** [comment]
Wouldn't it make sense to make this default! so the user doesn't have to do anything!

**Comment by Dudemanguy** [comment]
The defaults are basically my personal preference and I don't want the wheel to control changing pages. Nothing is stopping anyone for adding their own `WHEEL_UP` and `WHEEL_DOWN` bindings.

**Comment by Droyk** [comment]
> The defaults are basically my personal preference and I don't want the wheel to control changing pages. Nothing is stopping anyone for adding their own `WHEEL_UP` and `WHEEL_DOWN` bindings.

Wait one can't add alternative binding for a single function?

**Comment by Droyk** [comment]
I mean I want to control the changing pages via wheel up/down and by the arrow keys, I can't do it?

**Comment by Dudemanguy** [comment]
I'm not sure how you got that from my message. Of course you can add your own bindings to the mouse wheel. I just don't want one there by default.
