### ISSUE TITLE
keybinds clash

### ISSUE THREAD

**Issue by omaru-ok** [Dudemanguy/mpv-manga-reader#18]
the key `m`  lower is bound to `mute` 
and also in for reader at input.conf 
i made it bound `m script-message toggle-manga-mode `

but  its not working coz mpv think m = mute , not manga mode 

solution: 
-give proper way to achive only image based keybinds? mute is useless for images 
- in manga mode overwrite keys function with manga modes keys

**Comment by Dudemanguy** [comment]
This works for me. So does adding a binding in `input.conf`. Are you sure you actually started the manga reader?

**Comment by omaru-ok** [comment]
yes manga reader is started even i set it to   audo_start=yes 
but still mpv catches m as mute not magamode

**Comment by Dudemanguy** [comment]
I'm am fairly certain that `add_key_binding` will always override the default bindings. Even if it didn't, setting it in your input.conf should work anyways. Are you absolutely positive you don't have some other rogue script or something that sets this?

What happens if you try it with something like `mpv --no-config --script=/path/to/manga-reader.lua manga.zip`?

**Comment by omaru-ok** [comment]
`mpv  --no-config --script=./manga-reader.lua --log-file=manga.log .\Naruto\`
[manga.log](https://github.com/Dudemanguy/mpv-manga-reader/files/11182984/manga.log)

yes in vanila , it overwrite the default keys , worked well 

some question: 
![image](https://user-images.githubusercontent.com/108952834/230716394-a4ecb91c-02aa-48a1-b3b8-4826d74bf084.png)
why is this occuring?  **only** when i include manga reader 

when **not** including*   --script=./manga-reader.lua
![image](https://user-images.githubusercontent.com/108952834/230716557-a8552376-08ad-465f-b67b-4ddefe836dae.png)


when including --script=./manga-reader.lua
![image](https://user-images.githubusercontent.com/108952834/230716537-9f67ffc9-0cf6-4727-afa4-62fdff615d2b.png)

this occurred immediately when i pressed **`y`**

**Comment by Dudemanguy** [comment]
>yes in vanila , it overwrite the default keys , worked well

In that case, you must have some other script or something that is interfering with it.

>why is this occuring? only when i include manga reader

That's just a harmless warning. Manga writes to the playlist-pos property which can cause that.

>this occurred immediately when i pressed y

I would need a log for that case.

**Comment by omaru-ok** [comment]
first of all , everything is worked expect ~something
the new commit fixed the `playlist-pos` good  this is was needed
some workaround  for getting in work in ~ **my config** 
in **profiles.conf** added
[image]
-profile-cond=vid and not p["current-tracks/video/albumart"] and estimated_frame_count <= 1 
- load-scripts=no , scripts=~~/scripts/manga-reader.lua;

this din't worked too :( 
i have to explicitly put `auto_start`=yes  so it worked ! 
but key `y` is not showing anythign anymore? 

can you tell why is that happening? 
my mpv.conf has `no-input-default-bindings ` which block some of inbuild keys 
my input.conf for reference to reader 
```
## MANGA READER 
y script-message toggle-manga-reader
d script-message toggle-double-page
c script-message toggle-continuous-mode 
M script-message toggle-manga-mode 
l script-message next-page
h script-message prev-page 
Shift+l script-message next-single-page 
Shift+h script-message prev-single-page
Ctrl+l script-message skip-forward
Ctrl+RIGHT script-message skip-backward
HOME script-message first-page
END script-message last-page
k script-message pan-up 
j script-message pan-down
/ script-message jump-page-mode
ENTER script-message jump-page-go
ctrl+[ script-message jump-page-quit
```
some scripts i found to interfaring with .cbz  `quality-menu.conf`,`

wats the difference between `toggle-manga-mode: m` & `toggle-manga-reader: y` exactly?  please update readme with that too

**Comment by Dudemanguy** [comment]
`toggle-manga-reader` is what actually starts the script. It doesn't do anything unless you turn it on (`auto_start`) makes it always turn on. `toggle-manga-mode` just switches from right-to-left to left-to-right. It's completely different.

In theory you shouldn't need any of the autoprofile workaround, so I'm not sure what is happening there.

**Comment by omaru-ok** [comment]
im closing as my brain cells start to looss i dont knwo  how to fix without autoprofiling :(
