### ISSUE TITLE
double page: error

### ISSUE THREAD

**Issue by zaeboba** [Dudemanguy/mpv-manga-reader#19]
after turning on a double page, after a couple of pages this error appears and the player does not respond to any buttons (no it does not freeze, it's like reading manga and then accidentally press again "y")
![mpv_22 46 35](https://user-images.githubusercontent.com/57330346/235373540-6ea53610-bd15-4a49-b55e-dcb348905265.png)

**Comment by Dudemanguy** [comment]
Could you upload a sample where this happens?

**Comment by zaeboba** [comment]
Upload the manga? it weighs 1 gigabyte

**Comment by Dudemanguy** [comment]
I don't need the whole thing. Just the small set of pages where this error happens would work.

**Comment by zaeboba** [comment]
it does not occur on the same

**Comment by Dudemanguy** [comment]
That's a bit unfortunate. There's no way to make a small subset where error happens? If not, I guess downloading the whole thing is fine. I don't mind.

**Comment by zaeboba** [comment]
For example, the error appeared at once, only the browsing continued to work.
In your case, after entering read mode and watching manga, if you press "y" again, what happens? I, for example, mpv does not respond to any hotkeys, only closing the player and opening again.

Try pressing hotkeys, I use these
"home", "ctrl - right/left", "shift - right/left" 
without entering manga reading mode (m).

https://transfer.sh/GGy9zK/Tke5edqG32.mp4 - error demonstration video

https://drive.google.com/file/d/1vPEDiURd-1UMjilo7lgDtzpgcln4hnO2/view?usp=sharing - manga.

I don't know, maybe it's because it weighs a lot? I'm afraid to imagine what will happen to "berserk" which has three times the weight. 
Note the state of the player in the bar (demonstration video)

**Comment by Dudemanguy** [comment]
It's admittedly not perfect but should be usable now.
