### ISSUE TITLE
Image's format change on double page mode

### ISSUE THREAD

**Issue by sakuhanachan** [Dudemanguy/mpv-manga-reader#21]
As said in the title.
after enable Double page mode on some page, player will convert image's format (and color?) to same another image that open on double page.
like original is yuv444p but another image is gray, player will convert that yuv444p image to gray same as another image.
not sure it's happen on manga mode only or happen on normal mode too.

**example**
original: [dahliya6example.zip](https://github.com/Dudemanguy/mpv-manga-reader/files/12904653/dahliya6example.zip)
![mpv-shot0035](https://github.com/Dudemanguy/mpv-manga-reader/assets/2475440/40492dcb-5d27-4688-9665-3d55892bd1f7)

original: [inakaossan1example.zip](https://github.com/Dudemanguy/mpv-manga-reader/files/12904891/inakaossan1example.zip)
![mpv-shot0033](https://github.com/Dudemanguy/mpv-manga-reader/assets/2475440/dc81bb66-bc85-4ac5-830c-f3de0ded4233)

original: [romelia3example.zip](https://github.com/Dudemanguy/mpv-manga-reader/files/12904939/romelia3example.zip)
![mpv-shot0036](https://github.com/Dudemanguy/mpv-manga-reader/assets/2475440/75b73abe-8bd8-4a4f-bd59-fdc87e8eeb82)

**Comment by Dudemanguy** [comment]
It's because of lavfi-complex. I was never sure if there was a way to prevent that.

**Comment by Dudemanguy** [comment]
Sorry for the delay on this. The fix requires mpv from master to work.
