### ISSUE TITLE
Double page segmentation fault

### ISSUE THREAD

**Issue by NecRaul** [Dudemanguy/mpv-manga-reader#22]
I had previously thought this had something to do with changing the page on double page as other issues suggested and don't get me wrong, the segmentation fault happens whenever I change the page too but it happens when I do nothing as well.

Here's a [sample](https://files.catbox.moe/dfdye2.cbz) for replicating the issue, I chose one of the smaller chapters I could find on my collection.

Here's a [video](https://files.catbox.moe/w45zi0.mkv) of the issue happening.

Here's the [log](https://files.catbox.moe/le1e4o) of the issue happening.

- Happens in both X11 and Wayland.

- I have tried removing all the other scripts and using only this one.

- I have tried running mpv with minimal config setting.

- I have tried with both a cbz/cbr file and jpg/jpeg/png files.

**Comment by Dudemanguy** [comment]
It's an mpv bug. It's because I broke lavfi-complex before 0.36 (oops). It was fixed in https://github.com/mpv-player/mpv/commit/65840f8889a2a19610895c8223bbd1669448f062.

**Comment by NecRaul** [comment]
That's quite the timing lol, fixing it RIGHT after the release, guess I gotta compile it myself then, thanks.
