### ISSUE TITLE
Disable auto-window-resize when manga reader is active?

### ISSUE THREAD

**Issue by wiwaz** [Dudemanguy/mpv-manga-reader#23]
Currently manga where the resolution changes between pages results in mpv resetting the window size. This behavior is (imo) undesirable as it causes the window to jump around, and, if on windows unsnaps the window if you have it snapped onto a specific location.

**Comment by Dudemanguy** [comment]
I certainly don't want this behavior. You're welcome to set this in your config, but I don't this is something that's clearly 100% desirable and worth always enabling as an option in the script.
