### ISSUE TITLE
Auto_start and double being active in the config make normal mkvs shows display other tracks other than the ones already in the mkv

### ISSUE THREAD

**Issue by eldonita** [Dudemanguy/mpv-manga-reader#27]
I set the conf of the manga reader with auto_start to yes and double to yes but weirdly every time i open a normal mkv it will show other than the ones in the mkv ones from other episodes which shouldnt happen, disabling double seems to fix the problem but i would prefer to keep it active

**Comment by Dudemanguy** [comment]
I have no idea what you mean but this shouldn't even operate on mkv files in the first place given that it's not in the extension whitelist.

**Comment by eldonita** [comment]
i mean if in the manga-reader.conf i put 
auto_start=yes
double=yes
when i open cbz files it works normally but since i use mpv to watch animes or other shows too whenever i open them it weirdly loads more than one audio track and subtitles track and it shouldnt do it, if i remove the manga-reader.conf it loads everything normally 
![Screenshot 2024-02-20 145328](https://github.com/Dudemanguy/mpv-manga-reader/assets/121272988/c8b32beb-0fe1-4ca8-97bc-ba14e36d47d9)
![Screenshot 2024-02-20 145251](https://github.com/Dudemanguy/mpv-manga-reader/assets/121272988/2f99a6a5-34d5-4259-a36e-921729e9d5d0)

**Comment by Dudemanguy** [comment]
Can you upload a sample that shows this problem? I still don't really understand what's going on.

**Comment by eldonita** [comment]
> Can you upload a sample that shows this problem? I still don't really understand what's going on.
![Screenshot 2024-02-20 221650](https://github.com/Dudemanguy/mpv-manga-reader/assets/121272988/1c4a4b08-1890-493e-aa6a-213e5f01522d)
here i set the conf like this
and when i open a manga 
![Screenshot 2024-02-20 221303](https://github.com/Dudemanguy/mpv-manga-reader/assets/121272988/e16d9f21-b618-4b05-8c56-57d305637830)
everything works normally but when i open an mkv
![Screenshot 2024-02-20 222120](https://github.com/Dudemanguy/mpv-manga-reader/assets/121272988/cdcf837f-c4f9-4c63-975d-26aea18d54d1)
this happens and it shouldnt happen but when deleting the manga-reader.conf eveything work normally
![Screenshot 2024-02-20 222257](https://github.com/Dudemanguy/mpv-manga-reader/assets/121272988/ca9ff879-dd12-436f-bde8-49953faf11ff)
it seems like enabling double and auto_start in the config makes mpv load 2 files at the same time

**Comment by Dudemanguy** [comment]
Oh my bad, Can't believe I never noticed this.
