### ISSUE TITLE
compatible with other extensions #question

### ISSUE THREAD

**Issue by zaeboba** [Dudemanguy/mpv-manga-reader#33]
is it possible to implement this script to be compatible with other scripts? the only one that breaks its work is the visualizer.

Or should I write to the owner of the visualizer script?

**Comment by Dudemanguy** [comment]
What currently breaks? I don't really develop this with other scripts in mind, but I'm happy to make any changes to be more flexible.

**Comment by zaeboba** [comment]
it's hard to describe, it's just like everything's really laggy.
two pages down.
https://github.com/zaeboba/portable_config check out my build

**Comment by Dudemanguy** [comment]
Well I can't really replicate that setup but if the problem is with [this visualizer script](https://github.com/mfcc64/mpv-scripts/blob/master/visualizer.lua) that answer is pretty simple. Both my script and that one use lavfi-complex as well as the same hooks. There's not really much that can be done. They're not compatible scripts and you can't run both at the same time.

**Comment by zaeboba** [comment]
😭
so there's no way to differentiate between script activation?
or should I write to the developer and ask how to make the visualizer activate only on audio file extensions and not on cbz archives?

**Comment by AndreiVernon** [comment]
You could try something like

```
[Manga]
profile-desc="Manga"
profile-cond=filename and filename:match('%.cbz$') or filename:match('%.cbr$') or filename:match('%.zip$') or filename:match('%.rar$') ~= nil
script-opts-append=#whatever setting turns off the visualizer
```

It also seems like that vizualiser script has a mode=novideo setting which automatically turns off the visualizer if the file has a video feed. You could try that.

**Comment by Dudemanguy** [comment]
It is a limitation of mpv that the `--script` option cannot be easily modified on runtime, but it is possible to do a workaround using auto-profiles and `input-commands`. e.g. for reference see https://github.com/mpv-player/mpv/issues/14475#issuecomment-2203626467

You might not need something that complicated though if the above suggestion works.

**Comment by zaeboba** [comment]
I tried what Andrei wrote, I think it didn't work, or worked halfway, because:
1. there are still some hang-ups
2. the two-page mode doesn't work
I'm not sure if the video will make it clear what hangs we are talking about.

https://github.com/user-attachments/assets/72aec3bd-ad15-4c65-baac-3367d203a8ad

**Comment by Dudemanguy** [comment]
Do be clear, those problems do go away if you remove the visualizer script correct?

**Comment by zaeboba** [comment]
yes

**Comment by Dudemanguy** [comment]
The visualizer option would need some way for `visualizer_hook` to do a no-op instead of setting `lavfi-complex`. Both my script and that script write to that property and things just won't work if that happens.

**Comment by zaeboba** [comment]
Do I have to do something? I don't get it(((

**Comment by Dudemanguy** [comment]
Ask the script author to add an option to do nothing.

**Comment by zaeboba** [comment]
https://github.com/mfcc64/mpv-scripts/issues/36
I hope I've asked correctly and clearly

**Comment by zaeboba** [comment]
fixed
