### ISSUE TITLE
Pages are red in double page mode on latest mpv with gpu_next

### ISSUE THREAD

**Issue by McBaws** [Dudemanguy/mpv-manga-reader#34]
When in double page mode, the images appear red. This issue does not occur in single page mode or with vo=gpu.

Example screenshot:
![image](https://github.com/user-attachments/assets/d93ec06e-68e7-4cf4-a857-c38885dc88e3)

After some testing, I discovered that this issue started occurring on 20-21 Nov. 
My guess is that this commit is the culprit: https://github.com/mpv-player/mpv/commit/ef6052c01e323cece4ace135a1724fd09f86c86d

Here's an example test file:
[Bakuman example.zip](https://github.com/user-attachments/files/17878979/Bakuman.example.zip)

**Comment by Dudemanguy** [comment]
Can't reproduce. Shouldn't be a bug in the script though. This would likely be a problem with lavfi-complex.

**Comment by Lastnight-777** [comment]
I was able to reproduce on the latest version. 
After some testing, I found that the problem first occurs in 2024.11.21-git (shinchiro builds).
I did not change FFmpeg version during testing.

My guess is that recent changes caused this.

**Comment by Dudemanguy** [comment]
Gonna assume this was fixed upstream. Didn't keep track.
