### ISSUE TITLE
Zoom feature?

### ISSUE THREAD

**Issue by Obegg** [Dudemanguy/mpv-manga-reader#35]
Quite hard to read if you have a TV for example and the image itself is "zoomed out",
Isn't there any option to make the image fit to width of the monitor so that there will not be any black bars on the right and left side of the screen, and when user wants to read he will need to scroll down/up (as it's the current behavior with `UP` and `DOWN`)

**Comment by Dudemanguy** [comment]
You can set `--panscan=1` if you don't want black bars and `--video-align-y=-1` to align it from the top of the page.
