### ISSUE TITLE
`continuous` doesn't work

### ISSUE THREAD

**Issue by Obegg** [Dudemanguy/mpv-manga-reader#36]
it appears whenever i activate `continuous-mode` there's some kind of error..
when using `vo=gpu-next` it shows green screen all over the image, can't see anything besides the color green
when using `vo=gpu` it shows blue screen

**Comment by Dudemanguy** [comment]
That's normal. The final image is just too big for the gpu. Either use a software vo or decrease the `continuous_size`.
