### ISSUE TITLE
[PR-ish] some suggestions

### ISSUE THREAD

**Issue by NightMachinary** [Dudemanguy/mpv-manga-reader#5]
I find these options useful:
```
function mpv-manga() {
   mpv --no-config --load-scripts=no --script=~/.config/mpv/mpv-manga-reader/manga-reader.lua --image-display-duration=inf --input-conf=~/.config/mpv/input.conf --reset-on-next-file=video-pan-x,video-pan-y --video-align-x=1 --video-align-y=-1 --video-zoom=1 --fs --glsl-shaders="~~/shaders/Anime4K_3.0_Denoise_Bilateral_Mode.glsl:~~/shaders/Anime4K_3.0_Upscale_CNN_M_x2_Deblur.glsl" "$@"
}
```

Especially the https://github.com/bloc97/Anime4K shaders are game-changing.

I also made some changes [here](https://github.com/Dudemanguy/mpv-manga-reader/compare/master...NightMachinary:master).

I have some good hotkeys for zooming, panning, and switching glsl shaders in my [input.conf](https://github.com/NightMachinary/mpv-scripts/blob/master/input.conf).

PS: Perhaps I should just add this post to the wiki?

**Comment by Dudemanguy** [comment]
Seems like very opinionated changes to me. Well for the keybinding/option stuff, you can always just set your in your conf which is fine. The zoom-related things I have no strong opinion on however so maybe those can be changed.

**Comment by Dudemanguy** [comment]
All this stuff should be configurable now (finally added a `zoom_multiplier` option for continuous mode). Closing this now.
