### ISSUE TITLE
Dual page mode flicker when going to next/previous page

### ISSUE THREAD

**Issue by dtop129** [Dudemanguy/mpv-manga-reader#9]
As said in the title, whenever I go to the next or previous page in dual mode, the pages flicker for a second; this flicker is absent in single page mode.

**Comment by Dudemanguy** [comment]
There's nothing that can be done about this. The flicker is a result of turning the lavfi-complex off, loading the next file/video tracks, and then back on for the next two pages.

**Comment by Dudemanguy** [comment]
Late here but with the rewrite in 49cd401, it actually doesn't flicker at all anymore.
